version: '3.8'
services:
  btc-node:
    image: bitcoin/bitcoin:latest
    container_name: btc-node
    restart: always
    command: >
      sh -c "bitcoind -conf=/bitcoin.conf -datadir=/data
      -rpcuser=${BTC_RPC_USER}
      -rpcpassword=${BTC_RPC_PASSWORD}
      -rpcallowip=0.0.0.0/0"
    expose:
      - "8332" # BTC RPC
    ports:
      - "8333:8333" # BTC P2P
    volumes:
      - ./btc/data:/data
      - ./btc/bitcoin.conf:/bitcoin.conf
    env_file: .env
    healthcheck:
      test: ["CMD", "/opt/bitcoin-27.1/bin/bitcoin-cli", "-conf=/bitcoin.conf", "-rpcuser=${BTC_RPC_USER}", "-rpcpassword=${BTC_RPC_PASSWORD}", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blockchain_network

  fractal-node:
    image: fractalbitcoin/fractal:v0.2.1
    env_file: .env
    container_name: fractal-node
    restart: always
    command: >
      sh -c "bitcoind -conf=/bitcoin.conf -datadir=/data -maxtipage=504576000
      -rpcuser=${FRACTAL_RPC_USER}
      -rpcpassword=${FRACTAL_RPC_PASSWORD}
      -rpcallowip=0.0.0.0/0"
    expose:
      - "8332"
    ports:
      - "18333:8333"
    volumes:
      - ./fractal/data:/data
      - ./fractal/bitcoin.conf:/bitcoin.conf
    networks:
      - blockchain_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/bitcoin-cli", "-conf=/bitcoin.conf", "-rpcuser=${FRACTAL_RPC_USER}", "-rpcpassword=${FRACTAL_RPC_PASSWORD}", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bells-node:
    build:
      context: ./bells
      dockerfile: Dockerfile
    env_file: .env
    container_name: bells-node
    restart: always
    command: >
      sh -c "./bellsd -conf=/bells/bitcoin.conf -datadir=/data
      -rpcuser=${BELLS_RPC_USER}
      -rpcpassword=${BELLS_RPC_PASSWORD}
      -rpcallowip=0.0.0.0/0"
    expose:
      - "8332"
    ports:
      - "28333:8333"
    volumes:
      - ./bells/data:/data
      - ./bells/bitcoin.conf:/bells/bitcoin.conf
    networks:
      - blockchain_network
    healthcheck:
      test: ["CMD", "/opt/bells-3.0.0-rc2/bin/bells-cli", "-conf=/bells/bitcoin.conf", "-rpcuser=${BELLS_RPC_USER}", "-rpcpassword=${BELLS_RPC_PASSWORD}", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    build:
      context: ./node-dashboard
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file: .env
    networks:
      - blockchain_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file: .env
    networks:
      - blockchain_network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - dashboard
      - btc-node
      - fractal-node
      - bells-node
    networks:
      - blockchain_network

networks:
  blockchain_network:
    name: blockchain_network
    driver: bridge