version: '3.8'

services:
  btc-node:
    image: bitcoin/bitcoin:latest
    container_name: btc-node
    restart: always
    command: >
      sh -c "bitcoind -conf=/bitcoin.conf -datadir=/data
      -rpcuser=$${BTC_RPC_USER}
      -rpcpassword=$${BTC_RPC_PASSWORD}"
    environment:
      - BTC_RPC_USER=${BTC_RPC_USER}
      - BTC_RPC_PASSWORD=${BTC_RPC_PASSWORD}
    ports:
      - "8332:8332"  # BTC RPC
      - "8333:8333"  # BTC P2P
    volumes:
      - ./btc/data:/data
      - ./btc/bitcoin.conf:/bitcoin.conf
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-conf=/bitcoin.conf", "-datadir=/data", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain_network

  fractal-node:
    image: fractalbitcoin/fractal:v0.2.1
    container_name: fractal-node
    restart: always
    command: >
      sh -c "bitcoind -conf=/bitcoin.conf -datadir=/data -maxtipage=504576000
      -rpcuser=$${FRACTAL_RPC_USER}
      -rpcpassword=$${FRACTAL_RPC_PASSWORD}"
    environment:
      - FRACTAL_RPC_USER=${FRACTAL_RPC_USER}
      - FRACTAL_RPC_PASSWORD=${FRACTAL_RPC_PASSWORD}
    ports:
      - "18332:8332"
      - "18333:8333"
    volumes:
      - ./fractal/data:/data
      - ./fractal/bitcoin.conf:/bitcoin.conf
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-conf=/bitcoin.conf", "-datadir=/data", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - blockchain_network
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - blockchain_network
    depends_on:
    - btc-node
    - fractal-node
networks:
  blockchain_network:
    driver: bridge